[core]
reloadable = true
order = 0

[package]
version = "1.5.1"
category = "Simulation"
title = "Isaac Sim Samples"
description = "Sample extensions for Isaac Sim"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.vehicle" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.motion_planning" = {}
"omni.isaac.synthetic_utils" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.isaac.franka" = {}
"omni.isaac.manipulators" = {}
"omni.isaac.dofbot" = {}
"omni.isaac.universal_robots" = {}
"omni.isaac.motion_generation" = {}
"omni.graph.action" = {} 
"omni.graph.nodes" = {}
"omni.graph.core" = {}
"omni.isaac.quadruped" = {}
"omni.isaac.wheeled_robots" = {}

[[python.module]]
name = "omni.isaac.examples.tests"


[[python.module]]
name = "omni.isaac.examples.kaya_gamepad"

[[python.module]]
name = "omni.isaac.examples.omnigraph_keyboard"

[[python.module]]
name = "omni.isaac.examples.follow_target"

[[python.module]]
name = "omni.isaac.examples.path_planning"

[[python.module]]
name = "omni.isaac.examples.simple_stack"

[[python.module]]
name = "omni.isaac.examples.bin_filling"

[[python.module]]
name = "omni.isaac.examples.robo_factory"

[[python.module]]
name = "omni.isaac.examples.robo_party"

[[python.module]]
name = "omni.isaac.examples.hello_world"

[[python.module]]
name = "omni.isaac.examples.franka_nut_and_bolt"

[[python.module]]
name = "omni.isaac.examples.replay_follow_target"

[[python.module]]
name = "omni.isaac.examples.surface_gripper"

[[python.module]]
name = "omni.isaac.examples.unitree_quadruped"

[[python.module]]
name = "omni.isaac.examples.user_examples"

[[python.module]]
name = "omni.isaac.examples.ailab_examples"


[[test]]
timeout = 960
